In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
latlong = pd.read_csv('latlong.csv')

In [3]:
latlong.head()

     sector             coordinates
0  sector 1  28.3663° N, 76.9456° E
1  sector 2  28.5095° N, 77.0320° E
2  sector 3  28.4909° N, 77.0176° E
3  sector 4  28.4738° N, 77.0107° E
4  sector 5  28.4794° N, 77.0176° E

In [4]:

# Function to extract latitude and longitude
def extract_lat_lon(coord):
    try:
        lat, lon = coord.split(",")

        lat = float(lat.replace("° N", "").replace("° S", "").strip())
        lon = float(lon.replace("° E", "").replace("° W", "").strip())

        # South aur West ko negative bana do
        if "S" in coord:
            lat = -lat
        if "W" in coord:
            lon = -lon

        return pd.Series([lat, lon])

    except:
        return pd.Series([None, None])

In [5]:

latlong[["latitude", "longitude"]] = latlong["coordinates"].apply(extract_lat_lon)

In [6]:
latlong.drop(columns=["coordinates"], inplace=True)

In [7]:
latlong.head()

     sector  latitude  longitude
0  sector 1   28.3663    76.9456
1  sector 2   28.5095    77.0320
2  sector 3   28.4909    77.0176
3  sector 4   28.4738    77.0107
4  sector 5   28.4794    77.0176