In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
latlong = pd.read_csv('latlong.csv')

In [3]:
latlong.head()

     sector             coordinates
0  sector 1  28.3663° N, 76.9456° E
1  sector 2  28.5095° N, 77.0320° E
2  sector 3  28.4909° N, 77.0176° E
3  sector 4  28.4738° N, 77.0107° E
4  sector 5  28.4794° N, 77.0176° E

In [4]:

# Function to extract latitude and longitude
def extract_lat_lon(coord):
    try:
        lat, lon = coord.split(",")

        lat = float(lat.replace("° N", "").replace("° S", "").strip())
        lon = float(lon.replace("° E", "").replace("° W", "").strip())

        # South aur West ko negative bana do
        if "S" in coord:
            lat = -lat
        if "W" in coord:
            lon = -lon

        return pd.Series([lat, lon])

    except:
        return pd.Series([None, None])

In [5]:

latlong[["latitude", "longitude"]] = latlong["coordinates"].apply(extract_lat_lon)

In [6]:
latlong.drop(columns=["coordinates"], inplace=True)

In [7]:
latlong.head()

     sector  latitude  longitude
0  sector 1   28.3663    76.9456
1  sector 2   28.5095    77.0320
2  sector 3   28.4909    77.0176
3  sector 4   28.4738    77.0107
4  sector 5   28.4794    77.0176

In [2]:
odf = pd.read_csv('data.csv')

In [4]:
odf.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [17]:
sec = odf.groupby('sector')['agePossession'].value_counts().reset_index(name='count')
sec2 =sec.groupby('sector')['count'].sum().reset_index(name='total_count')

In [ ]:
sec.info

In [31]:
fdf = latlong.merge(sec, left_on='sector', right_on='sector', how='right')

In [32]:
fdf

                sector  latitude  longitude     price
0    dwarka expressway       NaN        NaN  1.372500
1          gwal pahari   28.4484    77.0210  3.192222
2              manesar   28.3515    76.9428  0.962258
3             sector 1   28.3663    76.9456  1.860000
4            sector 10   28.4537    77.0009  2.092857
..                 ...       ...        ...       ...
99           sector 92   28.4079    76.9153  0.934000
100          sector 93   28.4153    76.9326  0.848889
101          sector 95   28.4172    76.9081  0.480545
102          sector 99   28.4640    76.9614  1.008095
103         sohna road       NaN        NaN  0.662086

[104 rows x 4 columns]

In [34]:
fdf[fdf['latitude'].isnull()]

                sector  latitude  longitude     price
0    dwarka expressway       NaN        NaN  1.372500
75          sector 70a       NaN        NaN  2.199815
103         sohna road       NaN        NaN  0.662086

In [35]:
fdf

                sector  latitude  longitude     price
0    dwarka expressway       NaN        NaN  1.372500
1          gwal pahari   28.4484    77.0210  3.192222
2              manesar   28.3515    76.9428  0.962258
3             sector 1   28.3663    76.9456  1.860000
4            sector 10   28.4537    77.0009  2.092857
..                 ...       ...        ...       ...
99           sector 92   28.4079    76.9153  0.934000
100          sector 93   28.4153    76.9326  0.848889
101          sector 95   28.4172    76.9081  0.480545
102          sector 99   28.4640    76.9614  1.008095
103         sohna road       NaN        NaN  0.662086

[104 rows x 4 columns]

In [36]:
fdf.to_csv('final_data.csv', index=False)

In [3]:
df = pd.read_csv('final_data.csv')

In [7]:
df.head()

              sector  latitude  longitude     price
0  dwarka expressway   28.5570    77.1080  1.372500
1        gwal pahari   28.4484    77.0210  3.192222
2            manesar   28.3515    76.9428  0.962258
3           sector 1   28.3663    76.9456  1.860000
4          sector 10   28.4537    77.0009  2.092857

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sector     104 non-null    str
 1   latitude   104 non-null    float64
 2   longitude  104 non-null    float64
 3   price      104 non-null    float64
dtypes: float64(3), str(1)
memory usage: 4.3 KB

In [5]:
fig = px.scatter_map(
    df,
    lat="latitude",
    lon="longitude",
    color="sector",
    size="price",
)

In [43]:
fig.show()

In [ ]:
px.scatter_map(df,lat="latitude",lon="longitude",
               hover_name="sector", 
                map_style="satellite-streets",
                            size = "price",
                            color = "sector",
                            size_max=15, 
                            title="Population Distribution Across State",
                            zoom=10,
                            )

In [27]:
px.scatter_map(df,lat="latitude",lon="longitude",
               hover_name="sector", 
                map_style="carto-darkmatter",
                            size = "price",
                            color = "sector",
                            size_max=15, 
                            title="Population Distribution Across State",
                            zoom=10,
                            color_continuous_scale="Turbo"
                            )

In [31]:
fig = px.scatter_map(df,lat="latitude",lon="longitude",
               hover_name="sector",
                map_style="carto-darkmatter",
                            size = "price",
                            color = "sector",
                            size_max=15, 
                            title="Population Distribution Across State",
                            zoom=10,
                            color_continuous_scale="Turbo"
                            
                            )

In [1]:
neon = [
    "#FF1919", "#FF2619", "#FF3319", "#FF4119", "#FF4E19", "#FF5B19",
    "#FF6819", "#FF7619", "#FF8319", "#FF9019", "#FF9D19", "#FFAB19",
    "#FFB819", "#FFC519", "#FFD219", "#FFE019", "#FFED19", "#FFFA19",
    "#F6FF19", "#E8FF19", "#DBFF19", "#CEFF19", "#C1FF19", "#B3FF19",
    "#A6FF19", "#99FF19", "#8CFF19", "#7FFF19", "#71FF19", "#64FF19",
    "#57FF19", "#4AFF19", "#3CFF19", "#2FFF19", "#22FF19", "#19FF1D",
    "#19FF2B", "#19FF38", "#19FF45", "#19FF52", "#19FF60", "#19FF6D",
    "#19FF7A", "#19FF87", "#19FF95", "#19FFA2", "#19FFAF", "#19FFBC",
    "#19FFCA", "#19FFD7", "#19FFE4", "#19FFF1", "#19FFFF", "#19F1FF",
    "#19E4FF", "#19D7FF", "#19CAFF", "#19BCFF", "#19AFFF", "#19A2FF",
    "#1995FF", "#1987FF", "#197AFF", "#196DFF", "#1960FF", "#1952FF",
    "#1945FF", "#1938FF", "#192BFF", "#191DFF", "#2219FF", "#2F19FF",
    "#3C19FF", "#4A19FF", "#5719FF", "#6419FF", "#7119FF", "#7F19FF",
    "#8C19FF", "#9919FF", "#A619FF", "#B319FF", "#C119FF", "#CE19FF",
    "#DB19FF", "#E819FF", "#F619FF", "#FF19FA", "#FF19ED", "#FF19E0",
    "#FF19D2", "#FF19C5", "#FF19B8", "#FF19AB", "#FF199D", "#FF1990",
    "#FF1983", "#FF1976", "#FF1968", "#FF195B", "#FF194E", "#FF1941",
    "#FF1933", "#FF1926"
]

In [4]:
fig = px.scatter_map(
    df,
    lat="latitude",
    lon="longitude",
    color="sector",
    color_discrete_sequence=neon,
    size="price",
    hover_name="sector",
    map_style="carto-darkmatter",
    zoom=10,
    opacity=0.85,
    size_max=18
)

fig.update_traces(
    hovertemplate="""
<b>%{hovertext}</b><br>
Price: ₹%{marker.size:.2f} Cr<br>
<extra></extra>
"""
)

fig.update_layout(
     template="plotly_dark",
    height=400,
    margin=dict(l=0, r=0, t=50, b=0)
)

In [37]:
neon = [
    "#00FFFF", "#FF00FF", "#FFD700", "#39FF14",
    "#FF6EC7", "#00BFFF", "#FF4500", "#7FFF00",
    "#FF1493", "#1E90FF", "#ADFF2F", "#FFA500",
    "#8A2BE2", "#00FA9A", "#DC143C", "#40E0D0",
    "#FFFF00", "#FF69B4", "#7B68EE", "#00FF7F",
    "#FF6347", "#00CED1", "#BA55D3", "#F4A460"
]

# 24 colors × 5 = 120 colors
neon = neon * 5

In [6]:
df = pd.read_csv("data.csv")

In [7]:
px.histogram(
    df,
    x="price",
    nbins=50,
    title="Price Distribution"
)

# st.plotly_chart(fig, use_container_width=True)

In [ ]:

sector_price = (
    df.groupby("sector")["price"]
      .mean()
      .sort_values(ascending=False)
      .head(15)
)

fig = px.bar(
    sector_price,
    color=sector_price.index,
    title="Top 15 Expensive Sectors"
)
fig.show()
st.plotly_chart(fig, use_container_width=True)

In [ ]:
fig.show()

In [21]:
px.sunburst(
    df,
    path=["luxury_category", "property_type"],
    values="price",
    color="price",
    color_continuous_scale="reds",
    title="Luxury Category and Property Type Distribution"
)

In [ ]:

"Viridis"
"Turbo"      ⭐
"Plasma"
"Inferno"
"Cividis"
"Magma"
"Blues"
"Greens"
"RdBu"